export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Online Bank",
  headline: "Insert a headline in this section",
  description: "Insert information regarding the headline in this section",
  buttonLabel: "Get started",
  imgStart: false,
  img: require("../../images/svg-1.svg").default,
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: "discover",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Online Bank",
  headline: "Insert a headline in this section",
  description: "Insert information regarding the headline in this section",
  buttonLabel: "Get started",
  imgStart: true,
  img: require("../../images/svg-2.svg").default,
  alt: "any-devices",
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjThree = {
  id: "signup",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Online Bank",
  headline: "Insert a headline in this section",
  description: "Insert information regarding the headline in this section",
  buttonLabel: "Get started",
  imgStart: true,
  img: require("../../images/svg-3.svg").default,
  alt: "Stocks",
  dark: false,
  primary: false,
  darkText: true,
};
